API training script
Sanchelioss/script_practice pull request #7
Opened 2021-02-05 07:52 UTC by Sanchelioss

2021-02-05 07:59 UTC, mrkrot617 requested changes

2021-02-05 07:59 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +def get_weather_api():
get_weather_api_request

2021-02-05 07:59 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +	convert_to_json = request_to_API.json()
convert_to_json - это действие, надо переназвать

2021-02-05 07:59 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +def get_city_weather(convert_to_json):
когда ты назваешь метод словом get, оно подразумевает, что метод должен что-то вернуть. в твоем случае нужно либо переназвать метод на print, либо возвращать строку с погодой и печатать ее в теле скрипта

2021-02-05 07:59 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +	print("humidity: " + str(convert_to_json['main']['humidity']) + "%")
сделай правые части переменными и печатай переменные

2021-02-05 07:59 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +show_weather = get_city_weather(api)
твой метод ничего не возвращает, переменная тут не нужна

2021-02-05 08:35 UTC, Sanchelioss commented on scripts/python3_scripts/API_training.py
> +def get_weather_api():
fixed

2021-02-05 08:35 UTC, Sanchelioss commented on scripts/python3_scripts/API_training.py
> +	convert_to_json = request_to_API.json()
fixed

2021-02-05 08:36 UTC, Sanchelioss commented on scripts/python3_scripts/API_training.py
> +	print("humidity: " + str(convert_to_json['main']['humidity']) + "%")
fixed

2021-02-05 08:36 UTC, Sanchelioss commented on scripts/python3_scripts/API_training.py
> +show_weather = get_city_weather(api)
fixed

2021-02-05 08:39 UTC, mrkrot617 requested changes

2021-02-05 08:39 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +	json_format = api_responce.json()
responce_json

2021-02-05 08:39 UTC, mrkrot617 commented on scripts/python3_scripts/API_training.py
> +	temperature = ("temperature: " + str(int(json_format['main']['temp'] - 273)) + "C")
подсчет температуры раздели на два действия, сначала берешь кельвины, потом преобразуешь в новую переменную в цельсий

2021-02-05 10:13 UTC, Sanchelioss commented on scripts/python3_scripts/API_training.py
> +	json_format = api_responce.json()
fixed

2021-02-05 10:13 UTC, Sanchelioss commented on scripts/python3_scripts/API_training.py
> +	temperature = ("temperature: " + str(int(json_format['main']['temp'] - 273)) + "C")
fixed

2021-02-08 07:22 UTC, closed without merging

2021-02-08 07:22 UTC, Sanchelioss commented
Неактуально